### ISSUE TITLE
alpine build

### ISSUE THREAD

**Issue by mgoltzsche** [kafeg/ptyqt#3]
It would be great if ptyqt could be built on alpine as well.

Currently builds on alpine (musl libc) fail because `gettimeofday` and `_PATH_UTMPX` are not available:
```
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp: In member function 'virtual void ShellProcess::setupChildProcess()':
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp:412:5: error: 'gettimeofday' was not declared in this scope
  412 |     gettimeofday(&tv, 0);
      |     ^~~~~~~~~~~~
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp:419:15: error: '_PATH_UTMPX' was not declared in this scope; did you mean 'PATH_MAX'?
  419 |     utmpxname(_PATH_UTMPX);
      |               ^~~~~~~~~~~
      |               PATH_MAX
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp: In function 'char* pty_getproc(int, char*)':
../../../../liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp:464:27: warning: unused parameter 'tty' [-Wunused-parameter]
  464 | pty_getproc(int fd, char *tty) {
      |                     ~~~~~~^~~
make[3]: *** [Makefile:401: .obj/release-shared/unixptyprocess.o] Error 1
make[3]: Leaving directory '/go/liteide/build/src/3rdparty/ptyqt'
```
(I tried to build liteide x37.1 which contains this project.)

**Comment by kafeg** [comment]
Thank you for the report!

Was trying to build on alpine.

There is info about preparing build env, stored here just for the future builds:
1. Install alpine on VBox, run `apk add nano`
2. uncomment all repos in `/etc/apk/repositories`
3. run `apk update`
4. run `apk add build-base gcc abuild binutils cmake qt5-qtbase-dev qt5-qtwebsockets-dev double-conversion-dev pcre2-dev`

Then build like on Ubuntu: `git clone https://github.com/kafeg/ptyqt.git; cd ptyqt; mkdir build; cd build; cmake ..; cmake --build .`

Ok i fixed build in this commit https://github.com/kafeg/ptyqt/commit/be67327f2a67b28e62795d79eba8c241b02d297e

I hope everything will work now for you =)

**Comment by mgoltzsche** [comment]
Thanks @kafeg! It works now.
